### ISSUE TITLE
error in 1.3

### ISSUE THREAD

**Issue by Virusf** [alzamer2/Crunchyroll-XML-Decoder-py3#16]
I tested the new version but I have an error at startup 
![Sans titre](https://user-images.githubusercontent.com/48204427/68962696-77597000-07d5-11ea-8c17-191ac04b70be.png)

**Comment by alzamer2** [comment]
ok lets leave this issiue open and if you see any error report it here

**Comment by alzamer2** [comment]
ok i think i fixed it

**Comment by Virusf** [comment]
OK it seems to work

**Comment by Virusf** [comment]
you are testing option # 5 I had that
![Sans titre](https://user-images.githubusercontent.com/48204427/70344128-4232c180-1859-11ea-9cfd-5ef79290b956.png)

**Comment by alzamer2** [comment]
@Virusf  i think i fixed it.
can you try it out?

**Comment by Virusf** [comment]
OK it works very well

**Comment by Virusf** [comment]
hi and sorry but i still have a problem
![Cr](https://user-images.githubusercontent.com/48204427/73489871-a7afb400-43ab-11ea-8dba-8c26bc6e44aa.png)

**Comment by alzamer2** [comment]
> hi and sorry but i still have a problem
> ![Cr](https://user-images.githubusercontent.com/48204427/73489871-a7afb400-43ab-11ea-8dba-8c26bc6e44aa.png)

it seem they changed access_token
i updated it
i think this should fix this issue for you @Virusf

**Comment by Virusf** [comment]
It works very well
thank you

**Comment by darkhelmet2016** [comment]
Getting a different error in Version=1.3 when trying to update it gives the following error. Not sure if this is the program or just my pc choking on read/write permissions.

trying to close Crunchyroll-XML-Decoder-py3.......
Press any key to continue . . . Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\_pswindows.py", line 716, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\_pswindows.py", line 790, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\crunchy-xml-decoder\updater.py", line 80, in <module>
    run_update()
  File ".\crunchy-xml-decoder\updater.py", line 66, in run_update
    close_code()
  File ".\crunchy-xml-decoder\updater.py", line 39, in close_code
    pInfoDict = proc.as_dict(attrs=['pid', 'name', 'cmdline'])
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\__init__.py", line 638, in as_dict
    ret = meth()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\__init__.py", line 790, in cmdline
    return self._proc.cmdline()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\psutil\_pswindows.py", line 718, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=12852,
name='py.exe')

**Comment by alzamer2** [comment]
hmm i tried to use update and it worked for me
try to use it again
if it did not work try to update it manually from here

**Comment by Virusf** [comment]
Hello
I had to change HDD and reinstall everything
and now i have a problem but i don't know if it comes from me or from the program
`http://www.crunchyroll.com/fr/the-8th-son-are-you-kidding-me/episode-9-people-hate-me-are-you-kidding-me-794542
Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 645, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder\ultimate.py", line 95, in ultimate
    htmlconfig = json.loads(re.findall(r'vilos\.config\.media = ({.*})',html_page_)[0])
IndexError: list index out of range`

**Comment by alzamer2** [comment]
are you are account premium?
that episode is a premium user only atm

**Comment by alzamer2** [comment]
i tried 8 episode and it downloaded alright
and check if it region lock series 
dont forget you lost your old config file

**Comment by Virusf** [comment]
yes i have a premium account
and I redid the config file
but it wouldn't have a config to do on python or other ?

**Comment by Virusf** [comment]
I looked at the code and print before the error
and i got this
![{29828797-9E2D-471C-840A-8CAC2091BB2D} png](https://user-images.githubusercontent.com/48204427/83307963-17bd3200-a206-11ea-8d54-156af57865f2.jpg)

**Comment by alzamer2** [comment]
I'm looking into it, but from what printer it seem to be CF challnge issue

**Comment by alzamer2** [comment]
on side note 
can you post the link you used to download so i can paste and test it out
